### ISSUE TITLE
docker compose not working

### ISSUE THREAD

**Issue by cristiandiiorio** [11notes/docker-kms-gui#9]
Using the suggested docker compose returns this error:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
'name' does not match any of the regexes: '^x-'

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
services.kms-gui.depends_on contains unsupported option: 'restart'
```

I changed my docker-compose to this and it worked:
```
version: "3"

services:
  kms:
    image: "11notes/kms:stable"
    container_name: "kms"
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "var:/kms/var"
    ports:
      - "1688:1688/tcp"
    restart: "always"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:1688"]
      interval: 10s
      timeout: 5s
      retries: 3

  kms-gui:
    image: "11notes/kms-gui:465f4d1"
    depends_on:
      - kms
    container_name: "kms-gui"
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "var:/kms/var"
    ports:
      - "8080:8080/tcp"
    restart: "always"

volumes:
  var:

```

I hope this can help someone else. Thanks for your work on this project.

For reference I'm using:
Ubuntu 22.04
Docker version 28.0.1, build 068a01e
docker-compose version 1.29.2

**Comment by 11notes** [comment]
There is no error in the compose:

```
name: "kms"
services:
  kms:
    image: "11notes/kms:stable"
    container_name: "kms"
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "var:/kms/var"
    ports:
      - "1688:1688/tcp"
    restart: "always"
  kms-gui:
    image: "11notes/kms-gui:465f4d1"
    depends_on:
      kms:
        condition: "service_healthy"
        restart: true
    container_name: "kms-gui"
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "var:/kms/var"
    ports:
      - "8080:8080/tcp"
    restart: "always"
volumes:
  var:
```

You also don't need to add a healthcheck, all my images have a [healthcheck already](https://github.com/11notes/docker-kms/blob/master/arch.dockerfile#L75). Using ```version: "3"``` is deprecated.
